### ISSUE TITLE
Installing sketchy_topbar and sketchy_topbar

### ISSUE THREAD

**Issue by Meaticus22** [amsynist/dotfiles#1]
I'm trying to get your configuration for sketchybar seen in: https://github.com/FelixKratz/SketchyBar/discussions/47#discussioncomment-8307725 
<img width="865" alt="image" src="https://github.com/amsynist/dotfiles/assets/117058929/835eb951-e2c6-456d-97f2-04e1372a7db3">
**but** having trouble running the scripts after making them executable. 
<img width="1913" alt="image" src="https://github.com/amsynist/dotfiles/assets/117058929/8a6b4b79-74b8-4fa9-864e-109676c1147c">
_not sure If I am doing this right or not, first time posting an issue_
**contact @u/Meaticus22 for further discussions**

### Thank you!

**Comment by amsynist** [comment]
Hi @Meaticus22 

The setup you are trying to get is no more and i have purged those dotfiles permanently 

The current dotfiles point to below setup 


<img width="1680" alt="Screenshot 2024-05-05 at 18 04 18" src="https://github.com/amsynist/dotfiles/assets/50878560/f6acec25-ba3d-4c59-9eee-7e20fbb1e00f">

**Comment by Meaticus22** [comment]
No worries, thank you for responding.
